version: '2'

services:

    supplier-finder:
        ports:
            - 3000:3000
        build: .
        restart: always
        environment:
            NODE_ENV: production
            MONGODB_HOST: mongodb
        depends_on:
            - mongodb
        links:
            - mongodb
        command: npm start

    mongodb:
        ports:
            - 27017
        image: mongo:latest